development:
  adapter: mysql
  server: localhost
  username: root 
  database: teambox2_development
  host: 127.0.0.1
  encoding: utf8
  
test: &TEST
  adapter: mysql
  server: localhost
  username: root 
  host: 127.0.0.1
  encoding: utf8
  database: teambox2_test

production:
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: teambox2_production

cucumber:
  <<: *TEST